# Generated by Django 4.2 on 2023-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('SECOND_NAME', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('PHONE', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('QUALIFICATION', models.CharField(max_length=100)),
            ],
        ),
    ]
