# Generated by Django 4.2 on 2023-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='doc_profile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dept',
            field=models.CharField(max_length=100, verbose_name='Enter your Department '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter your Email '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Enter your First Name '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Enter your Last Name '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=100, verbose_name='Enter your Qualification '),
        ),
    ]
